[project]
name = "db-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fledge Shiu", email = "xzk0701@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "sqlalchemy[postgresql-psycopg]>=2.0.44",
]

[project.scripts]
db-models = "db_models:main"

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
