[project]
name = "document-ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fledge Shiu", email = "xzk0701@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.56.0",
]

[project.scripts]
document-ingestion = "document_ingestion:main"

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
